import Head from 'next/head';
import { Poppins } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import ThemeToggle from '@/components/ThemeToggle';
import BasicExample from '@/stories/BasicExample';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function Home() {
  const [activeTheme, setActiveTheme] = useState('light');

  useEffect(() => {
    if (typeof window === 'object') {
      document.body.dataset.theme = activeTheme;
      document.body.className = poppins.className;
      window.localStorage.setItem('theme', activeTheme);
    }
  }, [activeTheme]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main}`}>
        <ThemeToggle
          activeTheme={activeTheme}
          setActiveTheme={setActiveTheme}
        />
        <BasicExample />
      </main>
    </>
  );
}
